// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: internal/contracts/spaces.proto

package contracts

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SpaceStoreConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SpaceId       string                 `protobuf:"bytes,1,opt,name=space_id,json=spaceId,proto3" json:"space_id,omitempty"`
	Backend       string                 `protobuf:"bytes,2,opt,name=backend,proto3" json:"backend,omitempty"`
	MaxOperations uint64                 `protobuf:"varint,3,opt,name=max_operations,json=maxOperations,proto3" json:"max_operations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SpaceStoreConfig) Reset() {
	*x = SpaceStoreConfig{}
	mi := &file_internal_contracts_spaces_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpaceStoreConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpaceStoreConfig) ProtoMessage() {}

func (x *SpaceStoreConfig) ProtoReflect() protoreflect.Message {
	mi := &file_internal_contracts_spaces_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpaceStoreConfig.ProtoReflect.Descriptor instead.
func (*SpaceStoreConfig) Descriptor() ([]byte, []int) {
	return file_internal_contracts_spaces_proto_rawDescGZIP(), []int{0}
}

func (x *SpaceStoreConfig) GetSpaceId() string {
	if x != nil {
		return x.SpaceId
	}
	return ""
}

func (x *SpaceStoreConfig) GetBackend() string {
	if x != nil {
		return x.Backend
	}
	return ""
}

func (x *SpaceStoreConfig) GetMaxOperations() uint64 {
	if x != nil {
		return x.MaxOperations
	}
	return 0
}

type VerifierConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mode          string                 `protobuf:"bytes,1,opt,name=mode,proto3" json:"mode,omitempty"`
	AllowFake     bool                   `protobuf:"varint,2,opt,name=allow_fake,json=allowFake,proto3" json:"allow_fake,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifierConfig) Reset() {
	*x = VerifierConfig{}
	mi := &file_internal_contracts_spaces_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifierConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifierConfig) ProtoMessage() {}

func (x *VerifierConfig) ProtoReflect() protoreflect.Message {
	mi := &file_internal_contracts_spaces_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifierConfig.ProtoReflect.Descriptor instead.
func (*VerifierConfig) Descriptor() ([]byte, []int) {
	return file_internal_contracts_spaces_proto_rawDescGZIP(), []int{1}
}

func (x *VerifierConfig) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *VerifierConfig) GetAllowFake() bool {
	if x != nil {
		return x.AllowFake
	}
	return false
}

var File_internal_contracts_spaces_proto protoreflect.FileDescriptor

const file_internal_contracts_spaces_proto_rawDesc = "" +
	"\n" +
	"\x1finternal/contracts/spaces.proto\x12#workflow.plugins.encryptedspaces.v1\"n\n" +
	"\x10SpaceStoreConfig\x12\x19\n" +
	"\bspace_id\x18\x01 \x01(\tR\aspaceId\x12\x18\n" +
	"\abackend\x18\x02 \x01(\tR\abackend\x12%\n" +
	"\x0emax_operations\x18\x03 \x01(\x04R\rmaxOperations\"C\n" +
	"\x0eVerifierConfig\x12\x12\n" +
	"\x04mode\x18\x01 \x01(\tR\x04mode\x12\x1d\n" +
	"\n" +
	"allow_fake\x18\x02 \x01(\bR\tallowFakeBLZJgithub.com/GoCodeAlone/workflow-plugin-encrypted-spaces/internal/contractsb\x06proto3"

var (
	file_internal_contracts_spaces_proto_rawDescOnce sync.Once
	file_internal_contracts_spaces_proto_rawDescData []byte
)

func file_internal_contracts_spaces_proto_rawDescGZIP() []byte {
	file_internal_contracts_spaces_proto_rawDescOnce.Do(func() {
		file_internal_contracts_spaces_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_contracts_spaces_proto_rawDesc), len(file_internal_contracts_spaces_proto_rawDesc)))
	})
	return file_internal_contracts_spaces_proto_rawDescData
}

var file_internal_contracts_spaces_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_internal_contracts_spaces_proto_goTypes = []any{
	(*SpaceStoreConfig)(nil), // 0: workflow.plugins.encryptedspaces.v1.SpaceStoreConfig
	(*VerifierConfig)(nil),   // 1: workflow.plugins.encryptedspaces.v1.VerifierConfig
}
var file_internal_contracts_spaces_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_contracts_spaces_proto_init() }
func file_internal_contracts_spaces_proto_init() {
	if File_internal_contracts_spaces_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_contracts_spaces_proto_rawDesc), len(file_internal_contracts_spaces_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_contracts_spaces_proto_goTypes,
		DependencyIndexes: file_internal_contracts_spaces_proto_depIdxs,
		MessageInfos:      file_internal_contracts_spaces_proto_msgTypes,
	}.Build()
	File_internal_contracts_spaces_proto = out.File
	file_internal_contracts_spaces_proto_goTypes = nil
	file_internal_contracts_spaces_proto_depIdxs = nil
}
